# Generated by Django 4.2 on 2023-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_foto',
            field=models.CharField(default=12, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo_post',
            field=models.CharField(max_length=2000),
        ),
    ]
