# Generated by Django 4.2 on 2023-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_url_foto_alter_post_conteudo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_foto',
            field=models.CharField(max_length=5000),
        ),
    ]
