# Generated by Django 4.2 on 2023-04-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_url_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_foto',
            field=models.CharField(max_length=50000),
        ),
    ]
