# Generated by Django 4.2 on 2023-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_url_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curtidas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
