# Generated by Django 4.2 on 2023-04-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
