# Generated by Django 4.2 on 2023-04-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_curtidas_curtidas_post_total_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='mostrar',
            field=models.BooleanField(default=False),
        ),
    ]
