# Generated by Django 4.2 on 2023-04-24 20:07

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comentarios_mostrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo_post',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
